
version: '1.0'
services:
  # this is the web application we are going to test
  sentimentalyzer:
    build: ../
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:10.8.0"
    depends_on:
      - sentimentalyzer
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://localhost:8080
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e